[package]
name = "beth"
version = "0.1.0"
rust-version = "1.95"
edition = "2024"

[build-dependencies]
prost-build = "0.14.1"
protox = "0.9.0"
tonic-prost-build = "0.14.2"

[dependencies]
miette = "7.6.0"
clap = "4.6.6"
reth-ethereum = { git = "https://github.com/paradigmxyz/reth", tag = "v2.5.0", features = ["full"] }
tokio = { version = "1.53.1", features = ["full"] }

reth-node-builder = { git = "https://github.com/paradigmxyz/reth", tag = "v2.5.0" }
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth", tag = "v2.5.0" }
reth-node-api = { git = "https://github.com/paradigmxyz/reth", tag = "v2.5.0" }
reth-evm = { git = "https://github.com/paradigmxyz/reth", tag = "v2.5.0" }
reth-evm-ethereum = { git = "https://github.com/paradigmxyz/reth", tag = "v2.5.0" }
reth-payload-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v2.5.0" }
reth-basic-payload-builder = { git = "https://github.com/paradigmxyz/reth", tag = "v2.5.0" }
reth-chainspec = { git = "https://github.com/paradigmxyz/reth", tag = "v2.5.0" }
reth-ethereum-cli = { git = "https://github.com/paradigmxyz/reth", tag = "v2.5.0" }
reth-cli = { git = "https://github.com/paradigmxyz/reth", tag = "v2.5.0" }
reth-consensus = { git = "https://github.com/paradigmxyz/reth", tag = "v2.5.0" }
reth-ethereum-consensus = { git = "https://github.com/paradigmxyz/reth", tag = "v2.5.0" }
reth-ethereum-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v2.5.0" }
reth-execution-types = { git = "https://github.com/paradigmxyz/reth", tag = "v2.5.0" }
reth-ethereum-payload-builder = { git = "https://github.com/paradigmxyz/reth", tag = "v2.5.0" }
reth-ethereum-engine-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v2.5.0" }
reth-payload-builder-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v2.5.0" }
reth-transaction-pool = { git = "https://github.com/paradigmxyz/reth", tag = "v2.5.0" }
reth-storage-api = { git = "https://github.com/paradigmxyz/reth", tag = "v2.5.0" }
reth-primitives-traits = "0.6.0"
alloy-primitives = "1.6.1"
alloy-eips = "2.4.1"
eyre = "0.6.14"
thiserror = "2"
hex = "0.4"
prost = "0.14.1"
tonic = "0.14.2"
tonic-prost = "0.14.2"
